//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCentreFollowUps.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CallCentreTrackerEntities1 : DbContext
    {
        public CallCentreTrackerEntities1()
            : base("name=CallCentreTrackerEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public virtual DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public virtual DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public virtual DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public virtual DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public virtual DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public virtual DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public virtual DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public virtual DbSet<aspnet_Users> aspnet_Users { get; set; }
        public virtual DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public virtual DbSet<lutCheckInLevel> lutCheckInLevels { get; set; }
        public virtual DbSet<LutPhase> LutPhases { get; set; }
        public virtual DbSet<LutPhaseOutcome> LutPhaseOutcomes { get; set; }
        public virtual DbSet<LutPhaseStatu> LutPhaseStatus { get; set; }
        public virtual DbSet<LutScreeningPhase> LutScreeningPhases { get; set; }
        public virtual DbSet<lutStatu> lutStatus { get; set; }
        public virtual DbSet<tblAgent> tblAgents { get; set; }
        public virtual DbSet<vw_aspnet_Roles> vw_aspnet_Roles { get; set; }
        public virtual DbSet<vw_aspnet_Users> vw_aspnet_Users { get; set; }
        public virtual DbSet<vw_aspnet_UsersInRoles> vw_aspnet_UsersInRoles { get; set; }
        public virtual DbSet<InterviewOutcome> InterviewOutcomes { get; set; }
        public virtual DbSet<PhaseOutcome> PhaseOutcomes { get; set; }
        public virtual DbSet<tblAgentActivity> tblAgentActivities { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<tblRespondent> tblRespondents { get; set; }
        public virtual DbSet<tblStaging> tblStagings { get; set; }
    }
}
