//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCentreFollowUps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lutCheckInLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lutCheckInLevel()
        {
            this.tblRespondents = new HashSet<tblRespondent>();
        }
    
        public int CheckInLevelID { get; set; }
        public string CheckInLevel { get; set; }
        public string Discription { get; set; }
    
        public virtual lutCheckInLevel lutCheckInLevel1 { get; set; }
        public virtual lutCheckInLevel lutCheckInLevel2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRespondent> tblRespondents { get; set; }
    }
}
