//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCentreFollowUps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LutPhase
    {
        public int Id { get; set; }
        public int PhaseStatusId { get; set; }
        public int PhaseOutcomeId { get; set; }
        public string Description { get; set; }
    
        public virtual LutPhaseOutcome LutPhaseOutcome { get; set; }
        public virtual LutPhaseStatu LutPhaseStatu { get; set; }
    }
}
