//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCentreFollowUps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LutScreeningPhase
    {
        public int Id { get; set; }
        public string EligibilityCategory { get; set; }
        public string EligibilityDescription { get; set; }
        public int EligibilityCode { get; set; }
    }
}
