//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCentreFollowUps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRespondent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRespondent()
        {
            this.tblAgentActivities = new HashSet<tblAgentActivity>();
        }
    
        public int RespondentID { get; set; }
        public Nullable<int> ResonseId { get; set; }
        public Nullable<int> InstanceID { get; set; }
        public Nullable<int> RESPID { get; set; }
        public Nullable<System.DateTime> Q1 { get; set; }
        public string Q2 { get; set; }
        public string Q3 { get; set; }
        public Nullable<System.DateTime> Q202_EDD { get; set; }
        public string Resp_Surname { get; set; }
        public string Resp_FirstName { get; set; }
        public string Resp_Oth { get; set; }
        public string PhoneNumber { get; set; }
        public string Q607_C_1 { get; set; }
        public string Q608a_q608_C_1 { get; set; }
        public string Q609a_q609_C_1 { get; set; }
        public string Q610a_q610_C_1 { get; set; }
        public string Q611a_q611_C_1 { get; set; }
        public string Q612_Phone_C_1 { get; set; }
        public Nullable<System.TimeSpan> TimeZone { get; set; }
        public string Q610_ { get; set; }
        public Nullable<bool> CheckIn1 { get; set; }
        public Nullable<System.DateTime> CheckIn1Date { get; set; }
        public Nullable<bool> CheckIn2 { get; set; }
        public Nullable<System.DateTime> CheckIn2Date { get; set; }
        public Nullable<bool> CheckIn3 { get; set; }
        public Nullable<System.DateTime> CheckIn3Date { get; set; }
        public Nullable<bool> CheckIn4 { get; set; }
        public Nullable<System.DateTime> CheckIn4Date { get; set; }
        public Nullable<System.DateTime> EDD_Latest { get; set; }
        public Nullable<int> CheckInLevelID { get; set; }
        public string CheckInLevel { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string AddedBy { get; set; }
        public Nullable<int> CheckIn1StatusId { get; set; }
        public Nullable<int> CheckIn2StatusId { get; set; }
        public Nullable<int> CheckIn3StatusId { get; set; }
        public Nullable<int> CheckIn4StatusId { get; set; }
        public Nullable<int> CheckIn5StatusId { get; set; }
        public Nullable<bool> PhysicalAttempt1 { get; set; }
        public Nullable<bool> PhysicalAttempt2 { get; set; }
        public Nullable<bool> PhysicalAttempt3 { get; set; }
        public Nullable<bool> CheckIn5 { get; set; }
        public Nullable<System.DateTime> CheckIn5Date { get; set; }
        public Nullable<System.DateTime> PhysicalAttempt1Date { get; set; }
        public Nullable<System.DateTime> PhysicalAttempt2Date { get; set; }
        public Nullable<System.DateTime> PhysicalAttempt3Date { get; set; }
        public string VisitLevel { get; set; }
        public Nullable<int> ScreeningID { get; set; }
        public Nullable<int> InterviewID { get; set; }
        public Nullable<System.DateTime> ScreeningDate { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public Nullable<int> PhysicalAttemptStatusId1 { get; set; }
        public Nullable<int> PhysicalAttemptStatusId2 { get; set; }
        public Nullable<int> PhysicalAttemptStatusId3 { get; set; }
        public string ScreeningLevel { get; set; }
        public string InterviewerLevel { get; set; }
        public string PhaseStatus { get; set; }
        public string PhaseOutcome { get; set; }
        public Nullable<bool> ScreeningCheckIn { get; set; }
        public Nullable<bool> InterviewCheckIn { get; set; }
        public string interviewStatus { get; set; }
        public string InterviewOutcome { get; set; }
        public Nullable<int> CountryID { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual lutCheckInLevel lutCheckInLevel { get; set; }
        public virtual lutStatu lutStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAgentActivity> tblAgentActivities { get; set; }
    }
}
