//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallCentreFollowUps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStaging
    {
        public int St_Id { get; set; }
        public string id { get; set; }
        public string CellDescription { get; set; }
        public string technicalid { get; set; }
        public string cellid { get; set; }
        public string celltarget { get; set; }
        public string cellpreference { get; set; }
        public Nullable<int> CountryID { get; set; }
    }
}
